---
author: "Yuki Joyama"
date: "2023-10-24"
output: html_document
---
```{r message=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r message=FALSE}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Let's male a scatterplot

```{r message=FALSE}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```

Let's make a box plot
```{r message=FALSE}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

Let's make a bar plot!

```{r message=F}
nyc_airbnb |>
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~ neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```





